

title: SCITT
description: The Supply Chain Integrity, Transparency and Trust (SCITT) initiative is a set of proposed industry standards for managing the compliance of goods and services across end-to-end supply chains. 
# google_analytics: [Your Google Analytics tracking ID]